[project]
name = "llm-finetuning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib==3.10.6",
    "numpy==2.3.3",
    "tensorflow==2.20.0",
    "tiktoken==0.11.0",
    "torch==2.8.0",
    "urllib3==2.5.0",
    "pandas==2.3.3",
    "tqdm==4.67.1",
    "psutil==7.1.0",

]
